---
- hosts: all
  vars:
  - git_name: "Pawel Oczadly"
  - git_email: "paweloczadly@gmail.com"
  - go_path: "{{ ansible_env.HOME }}/dev/go"
  - zsh_plugins:
    - git
    - go
    - docker
  - zsh_theme: powerline
  - zsh_theme_settings:
      POWERLINE_RIGHT_A: exit-status-on-fail
      POWERLINE_HIDE_USER_NAME: true
      POWERLINE_HIDE_HOST_NAME: true
      POWERLINE_PATH: short
      POWERLINE_GIT_CLEAN: üòé
      POWERLINE_GIT_DIRTY: üí©
      POWERLINE_GIT_UNTRACKED: üêΩ
  roles:
  - { role: chrome, tags: ['chrome'] }
  - { role: firefox, tags: ['firefox'] }
  - { role: dropbox, tags: ['dropbox'] }
  - { role: vlc, tags: ['vlc'] }
  - { role: atom, tags: ['atom'] }
  - { role: dev-env, tags: ['dev-env'] }
  - { role: iterm2, tags: ['iterm2'] }
  - { role: oh-my-zsh, tags: ['oh-my-zsh'] }
  - { role: vim, tags: ['vim'] }
  - { role: git, tags: ['git'] }
  - { role: golang, tags: ['golang'] }
  - { role: docker, tags: ['docker'] }
  - { role: virtualbox, tags: ['virtualbox'] }
  - { role: vagrant, tags: ['vagrant'] }
  - { role: intellij, tags: ['intellij'] }
  - { role: cf, tags: ['cf'] }
