zsh_plugins:
- git
- go
- docker
zsh_theme: powerline
zsh_theme_settings:
  POWERLINE_RIGHT_A: exit-status-on-fail
  POWERLINE_HIDE_USER_NAME: true
  POWERLINE_HIDE_HOST_NAME: true
  POWERLINE_PATH: short
  POWERLINE_GIT_CLEAN: ğŸ˜
  POWERLINE_GIT_DIRTY: ğŸ’©
  POWERLINE_GIT_UNTRACKED: ğŸ½
