---
- name: install cli tools from brew
  homebrew: name={{ item }} state=present
  with_items: "{{ cli_utils }}"
  when: ansible_distribution == 'MacOSX'

- name: install cli tools from apt
  package: name={{ item }} state=present
  with_items: "{{ cli_utils }}"
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
